#define PROJECT_MAJOR_VERSION 0
#define PROJECT_MINOR_VERSION 1
#define PROJECT_PATCH_VERSION 0
#define PROJECT_VERSION       "0.1.0"
#define PROJECT_VERSION_W     L##"0.1.0"

#define PROJECT_NAME          "NAME_OF_PROJECT"
#define PROJECT_NAME_W        L"NAME_OF_PROJECT"

#define PROJECT_BUILD_TIME    "2024.05.02-20:23:41"
#define PROJECT_BUILD_TIME_W  L"2024.05.02-20:23:41"

#define PROJECT_C_VERSION     17
#define PROJECT_CPP_VERSION   20
